# Generated by Django 3.0.4 on 2020-03-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='long_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
