# Generated by Django 3.0.4 on 2020-03-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0002_auto_20200304_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='image_url',
        ),
    ]
