# Generated by Django 3.0.3 on 2020-03-07 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0003_auto_20200304_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spawn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField(blank=True, null=True)),
                ('rarity', models.CharField(blank=True, max_length=50, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loot.Container')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loot.Item')),
            ],
        ),
    ]
